# Site settings
title: 리디주식회사 RIDI Corporation
header-img: img/home-bg.jpg
email: start@ridi.com
description: "리디북스 서비스 제공 기업. 회사 소개 및 채용정보를 제공합니다."
url: "https://www.ridicorp.com"
enforce_ssl: www.ridicorp.com
baseurl: ""

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: pretty

gems:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

google_analytics:
  ua: "UA-10567409-3"

exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "config.ru", "Gemfile", "Gemfile.lock"]
